### ISSUE TITLE
Exposing the receive channel for events or passing a context into Recv()

### ISSUE THREAD

**Issue by matthewmueller** [mafredri/cdp#11]
It would be great to be able to have access to the raw channel behind the events to allow support select statements.

This is slightly contrived, but you should get the point:

```go
loadEventFired, err := c.Page.LoadEventFired(ctx)
if err != nil {
	return err
}

_, err = c.Page.Navigate(ctx, &cdpcmd.PageNavigateArgs{
	URL: "https://github.com",
})
if err != nil {
	return err
}

select {
case <-loadEventFired.Channel():
	return nil
case time.After(300 * time.Millisecond):
	return errors.New("timeout")
}
```

Alternatively if we could pass an additional context to (ie. `loadEventFired.RecvWithContext(ctx)`), that could work too.

The use case I need this for is after click events, where you may not know if the page is navigating or not so you need to wait a couple hundred milliseconds to see if a `Page. navigationRequested` has come in or not.

**Comment by mafredri** [comment]
This is actually something I have grappled with a bit, on the one hand it would be nice to expose a channel, but that would be at the cost of explicit error handling. My thought here is that `loadEventFired.Recv()` can produce an error if the `json.Unmarshal`ing fails, and in such a case, either no event would be emitted OR the user would have to remember to check the event for an error each time. Think `ev := loadEventFired.Recv(); if ev.Err() { return ev.Err() }; ...`.

In the current implementation there is never any worry of a *silent fail*, which I think is pretty valuable.

As I see it there are two ways to currently write what you are trying to accomplish.

The first version (as many lines as the original):

```go
loadTimeoutCtx, cancel := context.WithTimeout(ctx, 300 * time.Millisecond)
defer cancel()

loadEventFired, err := c.Page.LoadEventFired(loadTimeoutCtx)
if err != nil {
	return err
}

_, err = c.Page.Navigate(ctx, &cdpcmd.PageNavigateArgs{
	URL: "https://github.com",
})
if err != nil {
	return err
}

if _, err := loadEventFired.Recv(); err != nil {
	return err
}
```

And the second version, allowing a similar structure to the original:

```go
abort := make(chan error, 1)
loadEventFiredCh := make(chan cdpevent.PageLoadEventFiredReply, 1)

loadEventFired, err := c.Page.LoadEventFired(ctx)
if err != nil {
	return err
}
go func() {
	defer loadEventFired.Close()
	ev, err := loadEventFired.Recv()
	if err != nil {
		abort <- err
		return
	}
	loadEventFiredCh <- ev
}()

_, err = c.Page.Navigate(ctx, &cdpcmd.PageNavigateArgs{
	URL: "https://github.com",
})
if err != nil {
	return err
}

select {
case err := <-abort:
	return err
case <-loadEventFiredCh:
	return nil
case time.After(300 * time.Millisecond):
	return errors.New("timeout")
}
```

Opening multiple clients for the same event is not a problem.

The motivation for taking the context when we initiate the event client (`c.Page.LoadEventFired(ctx)`) instead of during `Recv()` is that we can think of it as opening a stream of events from the server that is active for the curation of the context. During this time, the client will buffer all events from the server until received via e.g. `Recv()`. When the context times out, is canceled, or the client (*stream*) is closed, the buffered events are released.

Does this make sense / help you?

**Comment by matthewmueller** [comment]
Awesome, thanks for your solid response @mafredri! I definitely agree in the value of explicit error handling. I'm currently rolling with option #2, but I wanted to see if there was any better way.

Regarding #1, I'd need to test it still, but wouldn't that `context.WithTimeout(ctx, 300 * time.Millisecond)` also cancel the navigation? It seems like it's not currently possible to do the following without an additional goroutine:

> After a navigation / mouse click occurs and is successfully acked, wait 300 milliseconds to see if there's been an event, otherwise timeout and move on.

**Comment by matthewmueller** [comment]
On more thought, this isn't really a big problem. I am making things more complicated using both navigation and mouse clicks as an example.

Since navigation is explicit, you can watch the loadEventFired. This works great.

My main reason for opening this issue was for implicit navigation like mouse clicks on links causing page navigation. While there's still a real possibility that the request/response via for Input.dispatchMouseEvent takes more than 300 milliseconds (or some small wait), it safe to say this is much less likely than a Page.navigate. And if you are noticing it taking longer than the allotted timeout, you can use a separate goroutine.

**Comment by mafredri** [comment]
@matthewmueller ah, you're absolutely right about it potentially cancelling navigation. That's an interesting use-case that I hadn't considered. Indeed the current event API is a bit limited in that regard.

I still think that the second method is best when needing a channel to communicate. It's a bit verbose, but it doesn't (tries not to?) make assumptions of how the API should be consumed. That said, I think there could be a use-case for `RecvContext(ctx)` in the event API.

One option would be to make `Recv()` take a context (breaking change) but I think the current implementation might be less confusing, avoids e.g. *why must I pass a context when creating an event client and receiving the event?*.

What do you think, would it make a useful addition?

---

**PS.** I thought of a third option which is more limited, but might potentially be *better* than the `RecvContext()`-method.

```go
loadEventFired, err := c.Page.LoadEventFired(ctx)
if err != nil {
	return err
}

_, err = c.Page.Navigate(ctx, &cdpcmd.PageNavigateArgs{
	URL: "https://github.com",
})
if err != nil {
	return err
}

go func() {
	time.Sleep(300 * time.Millisecond)
	loadEventFired.Close()
}

if _, err := loadEventFired.Recv(); err != nil {
	if cdp.ErrorCause(err) == rpcc.ErrStreamClosing {
		// Maybe not an error?
	}
	return err
}
```

(We could just as well use a `context.CancelFunc` instead of `(rpcc.Stream).Close()`.)

There are both pros and cons to this method, on the one hand we can't re-use the event client after this, but on the other hand we will also have closed the event client instead of accidentally using it later and receiving a stale (old) event from it. A `RecvContext()` method would leave the client open, and it could receive the event just moments after, a secondary call to `Recv` or `RecvContext` would return that event.

**Comment by matthewmueller** [comment]
> I still think that the second method is best when needing a channel to communicate. It's a bit verbose, but it doesn't (tries not to?) make assumptions of how the API should be consumed. That said, I think there could be a use-case for RecvContext(ctx) in the event API.

I had thought about this as well and I think this is a reasonable solution. I'm thinking this ctx would override the other context.

> One option would be to make Recv() take a context (breaking change) but I think the current implementation might be less confusing, avoids e.g. why must I pass a context when creating an event client and receiving the event?.

Yah, I like the current implementation more than having to pass two contexts in every time (in the rare case that the contexts should be different) and I think the solution above would be better DX. 

> What do you think, would it make a useful addition? (I'm still thinking about it).

I'm happy with whatever you decide here. My vote would probably be slightly in favor of adding `RecvContext(ctx)` over goroutines and channels, and I prefer that to a `Recv` API change.

We could also defer this change until it's more apparent that this a big deal and take it from there.

**Comment by mafredri** [comment]
> I had thought about this as well and I think this is a reasonable solution. I'm thinking this ctx would take precedent over the other ctx provided by the LoadEventFired(ctx).

Pretty much, the `ctx` provided to `RecvContext(ctx)` takes priority if it is aborted or times out first. However, it will not have any effect on the `ctx` provided to `LoadEventFired(ctx)`.

> I'm happy with whatever you decide here. My vote would probably be slightly in favor of adding `RecvContext(ctx)` over goroutines and channels and I prefer either option over a `Recv(ctx)` API change.

Thanks, I'll keep this in mind.

What do you think of an alternative, `loadEventFired.SetRecv{Deadline,Timeout}()`? This is a pretty common pattern in the standard library. I'm a bit worried that `RecvContext()` might result in *context overload*.

> We could also defer this change until if/when it's more apparent that this a common pattern and take it from there.

If it does not inconvenience you, I might like like to defer this for a little while, but not indefinitely. I do think it's a useful feature that should be present, so I also don't mind fast-tracking this 😄 .

**Comment by matthewmueller** [comment]
> What do you think of an alternative, loadEventFired.SetRecv{Deadline,Timeout}()? This is a pretty common pattern in the standard library. I'm a bit worried that RecvContext() might result in context overload.

Ahh interesting, that works too :-)

> If it does not inconvenience you, I might like like to defer this for a little while, but not indefinitely. I do think it's a useful feature that should be present, so I also don't mind fast-tracking this 😄 .

Not at all! I'd rather have more use cases to justify the change anyway.

**Comment by mafredri** [comment]
@matthewmueller I believe this use-case has been amended by `v0.10.0`.

The original code can now be written as follows:

```go
select {
case <-loadEventFired.Ready():
	// loadEventFired.Recv() - optional...
	return nil
case time.After(300 * time.Millisecond):
	return errors.New("timeout")
}
```

I'm glad we waited on this 😄!
