### ISSUE TITLE
Implement io.ReadCloser for the IO domain

### ISSUE THREAD

**Issue by mafredri** [mafredri/cdp#19]
The IO domain is used for streaming data (currently this is limited to tracing). In the future we might see stream in other parts as well (e.g. printing PDFs https://github.com/ChromeDevTools/devtools-protocol/issues/41).

It's possible to read until EOF and close streams, so we should be able to implement a `io.ReadCloser` quite painlessly.

Here's some pseudo-code (of `io.Reader`) to illustrate:

```go
func (r *ioReadCloser) Read(b []byte) (n int, err error) {
	if r.data {
		// Copy remaining data into b.
		return n, err
	}
	if r.eof {
		return 0, io.EOF
	}
	reply, err := r.c.IO.Read(ctx, &io.ReadArgs{
		Handle: &r.handle,
		Offset: &r.pos,
		Size: len(b),
	}
	r.eof = reply.EOF
	if reply.Base64Encoded != nil && *reply.Base64Encoded {
		// Handle base64 decoding.
	}
	// Copy reply.Data into b.
	// Store surplus in r.data?
	return n, err
}
```

Regarding `Size: len(b)`, this could also be defined when creating the reader, e.g. `io.NewStreamReader(bufsize int)`.

The reader could also be made to optionally *prefetch* the next chunk without waiting for the next call to Read. This would mandate a predefined buffer size.

**Sidenote:** It's a bit unfortunate that the IO-domain (`io`-package) conflicts name-wise with the standard library. Should we rename, and to what? Maybe `cio`, `cdpio`? Same goes for e.g. `log`.

**Comment by mafredri** [comment]
And now, support for IO.Streams has landed in PDFs as well: https://chromium.googlesource.com/chromium/src.git/+/4a31564e8305b41237a8c0f4a2e778612fd25e43.

**Comment by kevinbaijnath** [comment]
Hello @mafredri!  Thanks for all your great work on this project.

Is there any chance the PR linked above will be merged in?  I've run into a use case on my end where I need to rely on streaming to send back the generated pdf (due to the size being very large >200mb) and I would love to be able to use IOStreamReader.

**Comment by mafredri** [comment]
Hey @kevinbaijnath,

Yes, the end goal is to merge it. I've been undecided on the API, on the one hand I dislike `cdp.IOStreamReader` and think `io.StreamReader` would be nicer, but on the other, it's more discoverable as part of the `cdp` package. There's also one TODO in the code that needs to be addressed, but other than that that are no obstacles for merging it.

WRT the API, a third option would be to move it to `io.StreamReader`, and implement a method like `(*cdp.Client).NewStreamReader(ctx, stream)` which might be ideal considering it can't be used without the client (or underlying `rpcc.Conn`) anyway.

If you have a chance to use it before it's merged in, I would love some feedback

**Comment by kevinbaijnath** [comment]
Hey @mafredri, sorry for the delay, I was on vacation.

I've been experimenting with it in testing and it seems to be working well.  I have been able to generate .pdfs that are >200 mb pretty easily and haven't run into any issues yet.

I agree with you about the third option (moving it to io.StreamReader) because the underlying code needs to use the client anyway.  It might also make sense from an organization perspective because it is related to the IO package/domain.

**Comment by mafredri** [comment]
@kevinbaijnath it took a "while", but this is finally merged! It may require some refactoring since I moved the types around and renamed the functions, but functionally it's the same. Let me know if you find any issues with it.
