### ISSUE TITLE
Creating & activating a new target does not actually switch targets

### ISSUE THREAD

**Issue by djmally** [mafredri/cdp#33]
Hello,

In attempting to create new targets in the browser (i.e. multiple tabs), I've run into what I believe is a bug, in that when I create a new target and activate it using `Target.ActivateTarget`, the debugger is still attached to the old target. Strangely, calling `Target.CloseTarget` will close the newly-created target, but I still cannot seem to attach to it no matter what I do. I've attempted to close all targets when initializing the `cdp.Client`, but this returns an error and causes any subsequent target creation to fail with an error like `rpcc: the connection is closing`.

[Here's a gist exhibiting this behaviour](https://gist.github.com/djmally/188920c994feeaff9fd45f296e31b7d2) (relies on Chrome listening on localhost:9222).

**Comment by mafredri** [comment]
The behavior seems correct, however, the *Target* domain is not very well documented (as it is with most of the protocol) and I can totally understand how this could seem like a bug.

I'll try to be as clear and short as possible because this stuff is a bit confusing 😄.

#### Target-domain 

1. A target is essentially a `webSocketDebuggerUrl`, this is what you connect to
2. You can't detach from the target that you connected to (via `rpcc`), it's the only active communication channel with the browser
    * The browser end-point is preferable when working with multiple targets (more on this below)
3. `AttachToTarget` / `DetachFromTarget` only means that you can use use `SendMessageToTarget` and `ReceivedMessageFromTarget` to communicate with the target
    * See issue #10 for more information about this
4. `ActivateTarget` only focuses the target (tab in this case), might be necessary for screenshots/screencasts etc
5. When you close the Target that you connected to, you lose the only RPC connection that was established (this is why you see `rpcc: the connection is closing`)

#### The browser end-point

This `webSocketDebuggerUrl` is available for the lifetime of the browser and has less features than e.g. a `page`-target. It's preferable because it's not bound to any page, service worker, etc. It also makes it clear that the connection is only used to control targets. The url can be found either by:

```console
$ curl http://localhost:9222/json/version
```

Or on older versions of Chrome, `ws://localhost:9222/devtools/browser` should work.

However, working with this end-point requires (currently) a bit of extra work, as can be seen in #10.

#### Multiple connections

Another alternative is to use either the `Target` domain, or the `devtool` package to create new targets and connect to them separately via a new `rpcc` connection.

---

So, that's the gist of it. I do have plans to improve the ergonomics of working with the *Target*-domain, essentially abstracting away the `AttachToTarget`/`DetachFromTarget` methods. That work started in #10 but it hasn't been a priority and ended up on the back-burner.

Hope this helps, and don't hesitate to ask if you're still wondering about something!

**Comment by djmally** [comment]
Awesome awesome, thanks for such a detailed response! I'll try to play with `SendMessageToTarget`, even though it doesn't look very ergonomic at the moment. I think I can accomplish what I'm looking for given this info, it'll just be a little messy. Either way, this is a good clarification of the `Target` domain; I think the confusion I had stems mostly from how it works in [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface), which allows you to create a devtools connection, create multiple targets, and interact with them in the manner I had originally intended. My suspicion is that this library does something different under the hood, but I haven't dug in to figure it out yet.

**Comment by mafredri** [comment]
Ah, I see. AFAICT, chrome-remote-interface doesn't use the `Target` domain at all. Control and discovery is mostly centered around the `/json` API, similar to the `devtool` package in `cdp`. But CRI does make operating multiple targets more seamless 😄.

I'm glad my explanation helped, also, I've started to look at this problem again and started writing some code to implement it. I'll let you know how it progresses (this work, if completed, would essentially replace the `devtool` package for most use cases).

**Comment by djmally** [comment]
Just to give you an idea of how this ended up shaking out, I created a wrapper over `SendMessageToTarget` that effectively does the same thing as (what I believe is) the generated code for various domains. Essentially I create raw JSON messages like `{"id": 0, "method": "Page.navigate", "params": {"url": "http://www.example.com"}}` and send them directly to a target. Then, asynchronously, I have a listener that captures Target-domain events, and records them so that I can block on those events firing from other threads. This seems to work pretty well, although I haven't been able to capture events like `Page.loadEventFired` firing; does something in my methodology seem off?

**Comment by mafredri** [comment]
That sounds about right. The reason you're not seeing `Page.loadEventFired` could be that you have not called `Page.enable` first?

I'm happy to report the wrapping of Target/Browser is going pretty well (`package browser`). It will hide Create/Close Target, Send/Receive message from Target behind the normal rpcc.Conn/cdp.Client API. A simple use-case currently looks something like:

```go
// Connects to the browser via RPC (establishes a rpcc.Conn).
b, err := browser.Dial("localhost:9222")
if err != nil {
	return err
}

// NewPage returns the created target and connection (session).
newPage, conn, err := b.NewPage(ctx)
if err != nil {
	return err
}
defer newPage.Close() // Closes the page (Target) and disconnects any active sessions.
defer conn.Close() // Closes the connection (session).

c := cdp.NewClient(conn)
reply, err := c.Page.Navigate(ctx, page.NewNavigateArgs("https://www.google.com"))
if err != nil {
	return err
}
```

I'm still ironing out the API, but here's a taste (feedback welcome):

```
type Browser
    func Dial(ctx context.Context, addr string) (*Browser, error)
    func (b *Browser) Attach(ctx context.Context, t *Target) (*Session, error)
    func (b *Browser) Close() error
    func (b *Browser) Conn() *rpcc.Conn
    func (b *Browser) NewPage(ctx context.Context) (*Session, error)
    func (b *Browser) Pages() []*Target
    func (b *Browser) Quit() error
    func (b *Browser) Targets() []*Target
    func (b *Browser) Version(ctx context.Context) (string, error)
type Session
    func (s *Session) Close() error
    func (s *Session) Conn() *rpcc.Conn
type Target
    func (t *Target) Activate(ctx context.Context) error
    func (t *Target) Close() error
    func (t *Target) Info() *target.Info
```

I'm hoping to get this out before the weekend, but we'll see.

**Comment by mafredri** [comment]
@djmally I believe the reason you did not see any events might be due a recent change where I changed the Target messages from `string` to `json.RawMessage`. This was a mistake and I've reverted the change. My idea with this change was to delay the conversion to string but in hindsight this was a pointless change, sorry about that.

I noticed this because I was seeing responses like:

```
RECV: {"error":{"code":-32602,"message":"Invalid parameters","data":"message: string value expected"},"id":10}
```

I highly recommend enabling logging (e.g. see logging example in GoDoc) to debug these kinds of issues. This can usually give some indication as to where the error might lie.

**Comment by mafredri** [comment]
Hey @djmally, are you still using the `SendMessageToTarget` API? I would love it if you took a look at #41, it abstracts the API behind a `rpcc.Conn` so that it can be used with `cdp.Client`.

**Comment by djmally** [comment]
@mafredri yes I am, I would be happy to take a look!

**Comment by mafredri** [comment]
@djmally awesome! I just finished ironing out the rough edges. Let me know if you notice any weird behavior and I'll look into it.

I've temporarily left three `fmt.Printf` statements to help with debugging, so if you see something from `Client.watch`, I'd very much like to know 😄
