### ISSUE TITLE
Request Interception error

### ISSUE THREAD

**Issue by zfLQ2qx2** [mafredri/cdp#39]
I am trying to setup to intercept network requests:

```
url := "*"
rii := network.NewSetRequestInterceptionArgs([]network.RequestPattern{network.RequestPattern{URLPattern: &url}})
err = c.Network.SetRequestInterception(ctx, rii)
if err != nil {
  log.Fatal("SetRequestInterception error:", err.Error())
}
```

However, I receive the following error:

```
SetRequestInterception error:cdp.Network: SetRequestInterception: rpc error: 'Network.setRequestInterception' wasn't found (code = -32601)
```

This is with go1.8.3 and chrome 63. The chrome is latest, I can update go if it will resolve the issue.

**Comment by zfLQ2qx2** [comment]
Updated to go 1.9.2, same issue

**Comment by mafredri** [comment]
Sorry you ran into this, the Chrome developers renamed this method a while back from `Network.setRequestInterceptionEnabled` to `Network.setRequestInterception` (here's the commit in cdp https://github.com/mafredri/cdp/commit/c3ead3b01b7137201a0cca6ae7600ee7d1d50584#diff-e4ed50b15781f3b505130dd0e9193c2b).

You can either:
* Invoke the method manually with rpcc
* Update Chrome to 64 (recommended)
* Use an older version of cdp

Here's how you can invoke it manually:

```go
args := map[string]interface{}{
    "enabled": true,
    "patterns: []string{"*"},
}
reply := make(map[string]interface{})
err := rpcc.Invoke(ctx, "Network.setRequestInterceptionEnabled", args, reply, conn)
```

Instead of using maps, you could copy the structs from the old protocol definitions (see commit I linked to).

I would love to provide backwards compatibility when Chrome makes these breaking changes, but I haven't had the time to make it a reality.

**Comment by mafredri** [comment]
Oh and by the way: I recommend checking the [devtools protocol changelog](https://github.com/ChromeDevTools/devtools-protocol/blob/master/changelog.md) if you run into this in the future. [Here](https://github.com/ChromeDevTools/devtools-protocol/blob/master/changelog.md#roll-protocol-to-r510657) is where the change happened.

**Comment by zfLQ2qx2** [comment]
@mafredri Thank you! Was worth opening the issue just to learn about rpcc.Invoke!
