### ISSUE TITLE
Question: Advantage over JS libs?

### ISSUE THREAD

**Issue by dalu** [mafredri/cdp#55]
Does this have any performance advantage compared to JS libs?
Or does this construct js commands via the various function calls, then sends them to the browser?

**Comment by dalu** [comment]
So far, but it's comparing apples and oranges because with cdp I have a browser window already open and with puppeteer I don't, altough it can be  done with puppeteer to connect and disconned, but it's buggy and leads to segfaults.
So yeah, so far, cdp seems more stable and performs better than puppeteer, which is a high level js lib.
Only cdp has a steeper learning curve. But considering that Go is a simple language I was getting the same amoung of things done in less time than I was with puppeteer. ymmv.

**Comment by mafredri** [comment]
Hey, I'm glad you found cdp!

As you already noticed, cdp has a slight edge for being written in Go and can utilize concurrency better than single-threaded JS. I would say that performance gains from using `cdp` largely depend on the work-load. If a lot of the heavy lifting is done by the browser, then the performance gains will not likely be very significant.

Off the top of my head, here are some cases where I believe cdp has performance benefits:

* Operating many tabs/pages/browsers simultaneously
* Receiving large amounts of events / event payloads
    * Say, for example, if the DOM and Network domains have been enabled and the page is very chattery (lot's of DOM updates, many network requests). Then cdp benefits from concurrency and delayed processing (not all JSON is decoded unless it's used)

I agree that there is a very steep learning curve. Largely cdp just exposes the raw protocol in a form that's (hopefully) conveniently used in Go, but the protocol is complicated and sometimes the documentation is severely lacking :/. I'm considering introducing a new package that can provide helper functions for making some regular tasks more convenient. If you have suggestions on how to make cdp easier to use, I would be happy to hear your ideas!

I haven't used puppeteer, but I believe [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) is a more realistic comparison to cdp. Both are low-level (so to speak).

> But considering that Go is a simple language I was getting the same amoung of things done in less time than I was with puppeteer. ymmv.

Wow, this feels like high praise, or perhaps just a testament to your ability. Either way, I'm glad you're finding yourself productive with cdp, thanks 😄!

**Comment by dalu** [comment]
Yes I like it, but there needs to be something like a map.
All functions that take NodeID as an input parameter.
And if not that, improved documentation, something you can ctrl+f search.
(I mean the //comments above the functions).

And I found it's rather slow if chromium isn't on the same computer, not using 127.0.0.1:9222, but local network or even server on the internet (for now without wss, just ws).
`--disable-software-rasterizer` helps a little but not much.
*BUT* that is because a) on the local computer I use regular chromium from the Archlinux distribution and b) xeon-1275v5 cpu locally, while internetserver has xeon-1245v2 and localnet computer is an apu2c4 ("<2000 bogomips, 4 cores")
Running the same binary on the internet computer and it's running chromium canary headless aka headless_shell, probably with Debug symbols and all enabled, because I don't know how to build a production build, I just followed their headless_shell instructions where you create out/Debug/ and so on. And that took 4 1/2 hours to compile.

real	0m7.424s
user	0m0.043s
sys	0m0.043s

on the local computer:
0.01s user 0.02s system 8% cpu 0.353 total

on the apu2c4:
real	0m10.400s
user	0m0.264s
sys	0m0.144s


How would I even start?
This I what I'd like to build:
Do you know facebook debugger?
It's essentially a meta tag parser for opengraph meta tags.
In a way this is what I'd like to build.
When someone writes a micropost it should index the pasted links.
It should search for all audio/video links, all images, and meta tags.
At first it should parse meta tags and if they don't have og:image or og:audio or og:video etc available or dc.description or just description, it should try to extract them out of the visited page.
Then it should store those in a database.
That's all it should do.

This can then be used by another service to either initiate indexing or fetch already existing data and render a card with image and title, description, audio/video.
The foundation for any social network.

But each indexing task needs to run in its own page. If you have 1024 clients or open tabs simultaneously running. Not sure what the limits are there.
Why chromium? Because single page apps and data. Usually fetched data isn't indexed.

Next application of this, and why it should be chromium, rendering single page apps, especially Angular is a PITA with not being 100% indexed by Google or similar search engines. So there needs to be some backend that just does the equivalent of `chromium --dump-dom <url>`, triggered by escaped_fragment.
Likewise this should have a configurable cache or it should honor what the site sets as cache duration.

Of course the first could be done with just Go and there's an excellent scraper framework... forgot name.
But it doesn't do single page apps.

Then, puppeteer has conditions for determining page load complete...
`await page.goto(site, {waitUntil: 'networkidle0'});`
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options
Not sure what the conditions are here or if that's something higher level that puppeteer does on top of the protocol.

**Comment by mafredri** [comment]
> And if not that, improved documentation, something you can ctrl+f search.
(I mean the //comments above the functions).

Have you looked at the [GoDoc](http://godoc.org/github.com/mafredri/cdp) documentation for the project? I've tried to design the generated code in such a way as to get as much out of godoc as possible. I do see what you mean by easily discovering everything that takes e.g. a NodeID, it would be useful. It doesn't fit into godoc though, and I'm not sure how it could be exposed.

Usually the functions that take a certain type reside in the same domain, so e.g. the [dom](http://godoc.org/github.com/mafredri/cdp/protocol/dom)-package documentation would be searchable. I often also utilize ripgrep on my local file system to find relevant code.

> And I found it's rather slow if chromium isn't on the same computer, not using 127.0.0.1:9222, but local network or even server on the internet (for now without wss, just ws).

Interesting. I've been considering / working on an async-type API that would allow you to issue multiple commands to chrome without first waiting for each result (batch, if you will). It might help a little with the network latency in some cases.

Consider something like:

```go
replies := make([]dom.DescribeNodeReply, len(metaIDs))
// ...
err := asyncClient.
    DOM.DescribeNode(ctx, dom.NewDescribeNodeArgs().SetNodeID(metaIDs[0]), &replies[0]).
    DOM.DescribeNode(ctx, dom.NewDescribeNodeArgs().SetNodeID(metaIDs[1]), &replies[1]).
    Wait()
```

I'm not actually sure what the API would look like yet, but it could be the above, or perhaps something different (ideas welcome).

> How would I even start?

Though question 😄. I don't know the Facebook debugger, but I'll try my best to give you some pointers.

> It should search for all audio/video links, all images, and meta tags.

So there are two ways to do this. The first is (like you've done with meta previously) use query selector on the page and fetch them this way. The second is, enabling the DOM events (`c.DOM.Enable()`) in which case you can subscribe to the appropriate events for when the tags appear or are updated.

You can also utilize `cdp.Sync` to ensure events come in the right order, and similarly, the `<-eventClient.Ready()`-channel combined with a `select` allows you to only launch one goroutine to watch your events (I've been meaning to create an example of this, but at least it's used in the [`session`](https://github.com/mafredri/cdp/blob/13d613e9ad2a3673b0425ff6191201c304abc5b3/session/manager.go#L105-L150) package).

> But each indexing task needs to run in its own page. If you have 1024 clients or open tabs simultaneously running. Not sure what the limits are there.

I don't know the limits either, but headless operation will definitely consume less resources than when started without. Also, if you need multiple browsers (e.g. isolation), you can consider creating multiple BrowserContexts instead.

Also, using `rpcc.Dial` for each tab will consume more resources than e.g. using the [`session`](https://godoc.org/github.com/mafredri/cdp/session) package. One thing to note though, session connections suffer a bit in performance (if there is network lag) when used to control multiple tabs since I've yet to implement the async client (or async rpcc invokations).

> Then, puppeteer has conditions for determining page load complete...

To create something similar, I would track the network events (`RequestWillBeSent`, `ResponseReceived` and `LoadingFailed`). Then decide on a timeout for when the page is done loading which you initiate after the page has finished loading (`DOMContentLoaded`). With each network request, you cancel the timeout and when there are no longer any outbound network requests, initiate the timeout again (this is just the high-level idea).

For extra measure, you might also want to listen in on `Page.FrameStartedLoading` to detect if the page navigated to a new page, `Runtime.ExceptionThrown` to know if there were any errors, etc.

**Comment by matthewmueller** [comment]
Just chiming in here with my take since I've used both extensively:

I'd say it's mainly a JS vs Go issue. @mafredri has done an incredible job designing and developing CDP to work as advertised. Puppeteer is also really well done as it has a Google team backing it. 

I'd choose CDP over puppeteer wherever possible mostly because Go is easier to work with and maintain than Javascript. Whenever I run into issues with CDP, I also check the issues of puppeteer to see if they've resolved it. Normally it ends up being either my issue or an issue with chromium.

**Comment by dalu** [comment]
Well, I believe the purpose of the issue is satisfied, so I'll close it. People can still comment even if it's closed.
