### ISSUE TITLE
Open pages concurrently with multiple workers

### ISSUE THREAD

**Issue by danf0rth** [mafredri/cdp#60]
Hi! Thanks for this awesome package!
I try to create a concurrent web crawler, that will process all JS on the pages, and get the final HTML document.
This how i do it now:

0. Run chrome (`Google Chrome 69.0.3493.3 dev`) with `--headless` and `--remote-debugging-port=9222` flags.
1. Create the `devtool.DevTools` instance.
2. Spawn multiple workers (e.g. 2), and in each of workers i do following steps: 
  1. Make call to `devt.Get(ctx, devtool.Page)`
  2. Make call to `rpcc.DialContext(ctx, page.WebSocketDebuggerURL)`
  3. Make call to `cdp.NewClient(conn)` with rpcc connection opened before.
  4. Create event, e.g. `LoadEventFired`, etc.. and waiting for jobs from input channels.
  5. When job received, goroutine call `client.Page.Navigate(ctx, page.NewNavigateArgs(job))`, wait for fired event, and than call `client.DOM.GetDocument(ctx, nil)`

**The problem** is, when goroutine receive a job, and send the response to the responses chan, i receive same response for the different targets. So, for example, i send in channel two urls: `http://example.com/` and `http://awesomesite.net/`, and then in responses channel i get html code of first target `http://example.com` twice, so it looks like when my worker receive the new target, it cancel the job from previous, and then two of my workers react on the same event, and get the same html code.

What am i doing wrong, and how to do concurrent requests that will not cancel each other? 
Thank you!

**Comment by mafredri** [comment]
Hi, @danf0rth, glad you're enjoying it!

You should be able to fix the issue by using `devt.Create()` instead of `Get()`. The reason you're seeing the duplicated result is that both your workers are controlling the same tab. One worker issues navigate (or both, but one cancels the other) and both workers receive the same events.

Hope that helps!

PS. It's been on ice for a while, but I'm working on an additional package for `cdp` that would allow for better control of the browser via the Target domain (it would also utilize the `session` package). It might be of interest to you, I hope I'll have more news about it in the near future 😄.

**Comment by danf0rth** [comment]
I will check your new project, but this one covers my requirements for 100500%. Thanks for your reply, your advice helps to solve the problem, now everything works bellissimo. :+1:
