### ISSUE TITLE
How can I get the console log message with cdp ?

### ISSUE THREAD

**Issue by wanhl1990** [mafredri/cdp#63]
Hi all,  I want to get the console output , but I can't find the way to get them .  Anyone solve this ?

**Comment by mafredri** [comment]
You need to enable the Runtime domain (`c.Runtime.Enable`) and then you can use the `c.Runtime.ConsoleAPICalled` event client to receive the events/logs.

**Comment by wanhl1990** [comment]
> You need to enable the Runtime domain (`c.Runtime.Enable`) and then you can use the `c.Runtime.ConsoleAPICalled` event client to receive the events/logs.

Thanks for your reply. 
em... I have tried c.Runtime.ConsoleAPICalled and c.Console.MessageAdded function , but I don't get the console output. Code is.
`consoleCallclient ,err := c.Runtime.ConsoleAPICalled(ctx)
	if err != nil {
		fmt.Println(err)
		return err
	}
	defer consoleCallclient.Close()
	consoleCallclient.Ready()
	_,err = consoleCallclient.Recv()
	if err != nil {
		fmt.Println(err)
		return err
	}
	
	var log string
	consoleCallclient.RecvMsg(log)
	fmt.Println(log)`

Maybe it's a wrong method

**Comment by mafredri** [comment]
You don't need to look at the Console domain, it's deprecated and won't work for what you're trying to do.

Your first example looks correct (using `Recv`), are you making sure the application is logging to console? Try evaluating `console.log('hi');` via `c.Runtime.Evaluate` before calling `Recv`, or you could spin up a go routine which calls `Recv` in a for-loop.

You are also ignoring the output by doing `_, err = consoleCallclient.Recv()`, so you can instead do `consoleEvent, err := consoleCallclient.Recv()` and check what was logged.

The usage of `RecvMsg` is not as intended, log should be a pointer and the event must be json.Unmarshal:able into that type. For example:

```go
var log runtime.ConsoleAPICalledReply
err = consoleCallclient.RecvMsg(&log)
```

(But the `Recv()` method is the preferable way to do it in this case.)

---

PS. I hope you don't mind, I updated your comment with triple back-tick so that markdown understands it's a code-block.

**Comment by mafredri** [comment]
I’m glad you got it working! By the way, the `reply` is a RuntimeObject which implements Stringer for human readable output. So if it fits your use-case, you could use `reply.String()` instead of the JSON unmarshaling.
