### ISSUE TITLE
Ordering defer statements and closing event clients

### ISSUE THREAD

**Issue by yarikbratashchuk** [mafredri/cdp#7]
Hello, Mathias.

It seems like another stupid question, but i'm not ashamed to ask.
I'm trying to order defer statements:
```js
ctx, cancel := context.WithTimeout(context.Background(), 55*time.Second)

devt := devtool.New("http://127.0.0.1:9222")
page, err := devt.Create(ctx)
if err != nil {
	fmt.Print(err)
	return
}

conn, err := rpcc.DialContext(ctx, page.WebSocketDebuggerURL, rpcc.WithBufferSize(2048562), rpcc.WithCompression())
if err != nil {	
	fmt.Print(err)
	return
}

// wrong order
defer cancel()
defer devt.Close(nil, page)
defer conn.Close()

c := cdp.NewClient(conn)

abort := make(chan error, 2)

go func() {
	select {
	case <-ctx.Done():
	case err := <-abort:
		fmt.Printf("aborted: %s\n", err.Error())
		cancel()
	}
}()

if err = catchExceptionThrown(ctx, c.Runtime, abort); err != nil {
	fmt.Print(err)
	return
}
if err = catchLoadingFailed(ctx, c.Network, abort); err != nil {
	fmt.Print(err)
	return
}
...
```
but always get an error, even if also get a response.
So i think the problem is in order of defer statements.
Error messages differs from time to time:
```
aborted: cdp.Network: LoadingFailed Recv: rpcc: the connection is closing
cdp.Runtime: Evaluate: context canceled
aborted: cdp.Network: LoadingFailed Recv: context canceled
```
What is the right order of defer statements?
p.s: i have no errors if i just remove ```devt.Close()```, but i'm not sure that it is the right thing to leave target unclosed. What do U think?

Thanks a lot.

**Comment by mafredri** [comment]
> It seems like another stupid question, but i'm not ashamed to ask.

Not stupid, don't worry about it 🙂, contexts are so powerful for this kind of stuff, but they take a bit to wrap your head around. Also, I'm very interested to see how others try to use this library, so this is informative 😉.

> What is the right order of defer statements?

Go defers are executed bottom-up (last `defer` is executed first). Generally you want to defer immediately after you (successfully) create a new resource that should be cleaned up to avoid *forgetting* about it or losing it due to code changes.

Here's how I would write the first part:

```go
ctx, cancel := context.WithTimeout(context.Background(), 55*time.Second)
defer cancel()

devt := devtool.New("http://127.0.0.1:9222")
page, err := devt.Create(ctx)
if err != nil {
	fmt.Print(err)
	return
}
defer devt.Close(nil, page)

conn, err := rpcc.DialContext(ctx, page.WebSocketDebuggerURL, rpcc.WithBufferSize(2048562), rpcc.WithCompression())
if err != nil {	
	fmt.Print(err)
	return
}
defer conn.Close()
```

> So i think the problem is in order of defer statements.
> Error messages differs from time to time:

This because channels are non-deterministic, there's no telling which of two channels sends when both are ready to send.

To work around this issue I recommend creating a second context for managing event listeners:

```go
abortCtx, abortCancel := context.WithCancel(ctx)
defer abortCancel() // Always defer to ensure cleanup, even if called manually later.

if err = catchExceptionThrown(abortCtx, c.Runtime, abort); err != nil {
	fmt.Print(err)
	return
}

if err = catchLoadingFailed(abortCtx, c.Network, abort); err != nil {
	fmt.Print(err)
	return
}

// Do stuff...

// Cancel all event listeners listening for abort.
abortCancel()

// Success!
```

Now, this is almost complete, but there's one more thing that is needed for this to work. In the following code sample, the `if cdp.ErrorCause(err) == context.Canceled { ... }` is the interesting part:

```go
func catchExceptionThrown(ctx context.Context, runtime cdp.Runtime, abort chan<- error) error {
	if err := runtime.Enable(ctx); err != nil {
		return err
	}
	loadingFailed, err := runtime.ExceptionThrown(ctx)
	if err != nil {
		return err
	}

	go func() {
		defer loadingFailed.Close()
		for {
			ev, err := loadingFailed.Recv()
			if err != nil {
				if cdp.ErrorCause(err) == context.Canceled {
					// No error.
					return
				}
				abort <- err
				return
			}
			// Runtime exception.
			abort <- ev.ExceptionDetails
		}
	}()

	return nil
}
```

**NOTE:** We could also check for `context.DeadlineExceeded`, but since we are *closing* the listeners by calling cancel.

By doing it this way, the `abort`ers will be cleaned up by the time we are closing the connection so there should be no errors.

> p.s: i have no errors if i just remove `devt.Close()`, but i'm not sure that it is the right thing to leave target unclosed. What do U think?

It depends, if you are creating a new page each time you probably want to close it when you're done, otherwise you will end up with a lot of pages! On the other hand, if you re-use them then you can just use `devt.Get(ctx, devtool.Page)`. Note that Chrome always creates one initial page when it is launched.

It's should also be possible to use the [Target](https://godoc.org/github.com/mafredri/cdp#Target) domain to create new browser contexts that should work as an alternative to creating pages, however, I have not played around with it myself, so can't provide any insight there.

---

All that being said, there's also another alternative. Calling `(rpcc.Stream).Close()` on the listeners instead of using a context.

```go
func catchExceptionThrown(ctx context.Context, runtime cdp.Runtime, abort chan<- error) (func() error, error) {
	// Code to initialize listener.
	// ...

	return func() error {
		return loadingFailed.Close()
	}, nil
}
```

To use these in the previous example:

```go
closeExceptionThrown, err := catchExceptionThrown(ctx, c.Runtime, abort)
if err != nil {
	// Handle error...
}
defer closeExceptionThrown()
```

In this case, you would check for `cdp.ErrorCause(err) == rpcc.ErrStreamClosing` instead.

**Comment by yarikbratashchuk** [comment]
@mafredri, U are awesome. Very cool explanation, i have no words. It all works now. Amazing. 
Thanks a lot.

**Comment by mafredri** [comment]
I'm glad it was helpful 😄!
