### ISSUE TITLE
Lifting URL scheme restriction for DevTools.CreateURL

### ISSUE THREAD

**Issue by nya3jp** [mafredri/cdp#70]
DevTools.CreateURL currently refuses to open URLs whose scheme is not http/https.

https://github.com/mafredri/cdp/blob/master/devtool/devtool.go#L80

This is a bit problematic for me because I often want to open other URLs, such as chrome://.

What do you think about lifting the restriction? Or at least adding "chrome" scheme to the whitelist is very helpful.

Thanks!

**Comment by mafredri** [comment]
I'm open to lifting the restriction. My reason for adding it is to prevent issues like `CreateURL("www.google.com")` which would open a blank page. The reason is that the `/json/new` API only accepts valid URLs (e.g. `http://`, `ftp://`, etc) and I guess I excluded all other options because why would anyone use `cdp` on a non-http URL, right 😏?

Perhaps the best approach would be to parse via e.g. `url.Parse` and set `Scheme` to either `http` or `https` if it's missing? Would you like to submit a PR?

**Comment by nya3jp** [comment]
Thanks for the background. Yes, usually http/https should be sufficient and my use case might be a bit exceptional :)

It makes perfect sense to check if a URL has scheme. But it's missing, I'm not sure which scheme to add (http or https?). How about just rejecting such URLs? Actually the current behavior is to reject them, so I believe such change does not harm usability.

I'll go ahead and create a PR. Thank you!
