### ISSUE TITLE
Unable to set input value

### ISSUE THREAD

**Issue by h7kanna** [mafredri/cdp#8]
Hi @mafredri ,

Trying to use this package for page automation.
Login page has input of type text. But I get rpc error when trying to set input value. The input can be found on the page though(I can print all the attributes). Below are error string and code. What I am  missing here? It can be something really basic. Please help if you can.

**Error** : 
cdp.DOM: SetNodeValue: rpc error: Can only set value of text nodes (code = -32000)

**Code Snippet**:
email, err := c.DOM.QuerySelector(ctx, cdpcmd.NewDOMQuerySelectorArgs(doc.Root.NodeID, "input#email"))
if err != nil {
	fmt.Println(err)
}

err = c.DOM.SetNodeValue(ctx, cdpcmd.NewDOMSetNodeValueArgs(email.NodeID, "test@test.com"))
if err != nil {
	fmt.Println(err)
}

**Comment by mafredri** [comment]
Hi @h7kanna, I hope you're liking the library so-far (if not, let me know what can be improved ;-)).

> Can only set value of text nodes

I think this error message hints at that `SetNodeValue` can only be used for text elements, e.g. `p` or similar.

You could try to use `SetAttributeValue` instead (since `value` is an attribute of the `input` element).

Something like:

```go
err = c.DOM.SetAttributeValue(ctx, cdpcmd.NewDOMSetAttributeValueArgs(email.NodeID, "value", "test@test.com"))
// ...
```

I hope this helps, if not, I'm going to be away until Friday and won't be able assist until then, but the good folks over at [ChromeDevTools/devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol/issues) should be able to help.

**Comment by h7kanna** [comment]
Hi @mafredri, 
Thanks. Let me try your suggestion.
Its looking like a promising project, planning it use and contribute.

**Comment by zmajew** [comment]
Hello, thanks for helping us here.
I have followed your suggestion and if fills the input field with email string when the new tab is opened but only for a fraction of second, and then it deletes it.

**Comment by mafredri** [comment]
@zmajew it sounds like the page is deleting the content via JavaScript, have you tried delaying the process?

**Comment by zmajew** [comment]
Thanks for the prompt reply. I tray with a delay with no success. I did it with 'input' package. I found how to do it following methods in MontFerret scraping framework. Are there any more examples for cdp package in general?

**Comment by mafredri** [comment]
If you provide a sample code that reproduces the issue I might be able to help, unfortunately I don't know of any good source of examples. There's the examples section in GoDoc which is enough to get started, there's also some good information in closed issues, but other than that you pretty much have to check the documentation for what functions are available and test your way forward 😄. The Chrome DevTools protocol isn't very well documented 😅.
