### ISSUE TITLE
CDP vs ChromeDriver

### ISSUE THREAD

**Issue by x777** [mafredri/cdp#86]
Hi, what real difference about CDP and ChromeDriver? I mean purpose of using. For example, if need make some user behaviour (click, form submit) on some different site from client side. Basic stuffs.
Explain me please because I see that CDP with Golang is not easiest way to drive browser. Thanks

**Comment by mafredri** [comment]
The purpose of `cdp` is to interact with the Chrome DevTools Protocol (née Chrome Debugging Protocol) which enables low-level control of the browser. This means you can control tabs, change window sizes, open incognito profiles, intercept network requests, emulate different devices / media, etc. It's quite different compared to ChromeDriver  which speaks the [WebDriver Wire Protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol) and is meant for browser automation / testing. Due to its nature and purpose, ChromeDriver provides many convenience functions for automating UI interaction. This is not the case for cdp since it operates on a lower-level, it can do the same things but it will require writing the code to do it.

That said, cdp would make an excellent base for creating a an automation library for the browser. I've seen a few project attempt this but I don't know what the current status of them are (e.g. [dtynn/chromy](https://github.com/dtynn/chromy) and [grooveid/chromecontrol](https://github.com/grooveid/chromecontrol), maybe others as well).

I have a vision of creating helper function/methods in cdp, as a sub-package or separate project to simplify e.g. mouse clicking, keyboard typing, etc. But I have yet to get around to it 😄.
