### ISSUE TITLE
Proxy setup

### ISSUE THREAD

**Issue by biter777** [mafredri/cdp#94]
Hi Mafredri!
Thnx for your cdp package!

Please tell me, how I can a setup proxy (http, socks)?

**Comment by mafredri** [comment]
Hi @biter777!

How do you usually configure proxy for your Go programs? I'm asking mostly because I don't have a clear picture of your use-case, and haven't really dealt with proxies myself.

I looked at the `gorilla/websocket` package and it seems they enable environment proxy configuration by default. Would it be sufficient for you if we did that here as well? I pushed a branch with the change, if you wish to take a look: https://github.com/mafredri/cdp/commit/cf94d30724582cce4d8e03ec110fb39e6dc980b4.

Another option would be to expose a new dial option that sets the proxy on the websocket dialer but I'm a bit adverse to it since it's pretty much an implementation detail of the `gorilla/websocket` package. I'm also considering other websocket libraries (e.g. `nhooyr/websocket`) and as such it would be unfortunate to expose this aspect of `gorilla/websocket`.

And a third option is to provide the dialer yourself. The `rpcc` package is designed so that the websocket implementation can be switched out by using the [rpcc.WithDialer](https://godoc.org/github.com/mafredri/cdp/rpcc#WithDialer) option. It works out of the box if the websocket connection implements `io.ReadWriteCloser`, but even if it doesn't, it can be wrapped quite easily. As an example, this is how it's done for `gorilla/websocket`: [rpcc/socket.go#L15-L59](https://github.com/mafredri/cdp/blob/a3cd6cc58c0b7537b9614e7fa5da84bdd3c18514/rpcc/socket.go#L15-L59).

**Comment by biter777** [comment]
I want chrome to make a connection through a proxy.
Now I just run chrome with `"--proxy-server="username:password@host:port"`.
But i'm not very familiar with devtools, I would like to be able to change the proxy in chrome in runtime without restarting chrome.

If I use a proxy in rpcc, then, as I understand it, it only affects the connection between go and chrome (correct me if I am wrong).

**Comment by mafredri** [comment]
Ah, then I believe you are doing it the right way (by running Chrome with the proxy flag). I took a look through the DevTools API and I didn't find any way to specify a proxy, so it doesn't seem possible (at this time).

If it's a feature you think should be there, I recommend opening a new issue on the chromium issue tracker to request it.

> If I use a proxy in rpcc, then, as I understand it, it only affects the connection between go and chrome (correct me if I am wrong).

Yeah, that's correct. At first I thought it was what you were after 😄.

**Comment by biter777** [comment]
Ok! Thanks you! :)
